#!/usr/bin/env bash
# "factors challenge!"

check_factor()
{
	if [ $# -ne 3 ];
        then
                args=("$@")
                count=0
                number2=1
                for a in ${args[*]};
                do
                        if [ $count -gt 1 ];
                        then
                                number2=$(echo $a*$number2 | bc)
                        fi
                        count=$((count + 1))
                done
        else
                number2=$3
        fi

        number1=$2
        number=$(echo "$1" | tr ':' '=')

        result=$(echo "if($number2 > $number1) 1 else 0" | bc)
	        if ((result == 1)); then
		        tmp=$number1
		        number1=$number2
		        number2=$tmp
                fi

        echo "$number$number1*$number2"
}

if [ $# -ne 1 ]
then
        echo 'Usage: factors <file>'
        exit 1
else

        while read i
        do

                result=$(factor "$i")
                check_factor $result

        done < "$1"
fi
