#!/usr/bin/python3

import sys
import math


def factorize(number):
    for i in range(2, int(math.sqrt(number)) + 1):
        if number % i == 0:
            print(f"{number}={i}*{number // i}")
            return
    print(f"{number}={1}*{number}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python factors.py <file>")
        return

    file_path = sys.argv[1]
    with open(file_path, "r") as file:
        for line in file:
            number = int(line)
            factorize(number)


if __name__ == "__main__":
    main()
